name: On Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up
      run: apt-get update && apt-get install -y make

    - name: Build
      run: make

    - name: Test
      run: echo lol
